1.导入numpy库并简写为np

In [1]:
import numpy as np

2.打印numpy的版本和配置说明

In [2]:
print(np.__version__, '\n')
print(np.show_config())

1.16.4 

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/89500/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/89500/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/89500/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\li

3.创建一个长度为10的空向量

In [3]:
E = np.empty((10, 1))
print(E)

[[4.67296746e-307]
 [1.69121096e-306]
 [1.16821216e-307]
 [1.89146896e-307]
 [1.37961302e-306]
 [1.05699242e-307]
 [8.01097889e-307]
 [1.33512308e-306]
 [9.79103798e-307]
 [1.24610927e-306]]


4.如何找到任何一个数组的内存大小？

In [4]:
Z = np.zeros((10, 100))
print('{} bytes'.format(Z.size * Z.itemsize)) # 此时Z.size = 1000，Z.itemsize = 8

8000 bytes


5.如何从命令行得到numpy中add函数的说明文档？

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

6.创建一个长度为10并且只有第五个值为1的零向量

In [6]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7.创建一个值域范围由10到49的向量

In [7]:
Z = np.arange(10, 50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8.反转一个向量

In [8]:
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


9.创建一个3x3且值从0-8的矩阵

In [9]:
Z = np.arange(9).reshape((3, 3))
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10.找到数组[1, 2, 0, 0, 4, 0]中的非0元素

In [10]:
nz = np.nonzero([1, 2, 0, 0, 4, 0])
print(nz)

(array([0, 1, 4], dtype=int64),)


11.创建一个3x3的单位矩阵

In [11]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12.创建一个3x3x3的随机数组

In [12]:
Z = np.random.random((3, 3, 3))
print(Z)

[[[0.24912228 0.2987383  0.24957569]
  [0.5695651  0.93918341 0.71780291]
  [0.27272424 0.16416442 0.24919534]]

 [[0.49485347 0.08565649 0.6411252 ]
  [0.7321943  0.6655075  0.62327877]
  [0.44634861 0.51523428 0.3349821 ]]

 [[0.11680496 0.8250613  0.22498019]
  [0.428414   0.08008234 0.21324175]
  [0.41839198 0.51325434 0.79620194]]]


13.创建一个10x10的随机数组并找到它的最大值和最小值

In [13]:
Z = np.random.random((10, 10))
print('The maximum is: {}. The minimum is: {}'.format(Z.max(), Z.min()))

The maximum is: 0.9981344311604371. The minimum is: 0.020725086332222475


14.创建一个长度为30的随机向量并找到它的平均值

In [14]:
Z = np.random.random(30)
print('The mean value is: {}'.format(Z.mean()))

The mean value is: 0.43523732954267824


15.创建一个二维数组，除了边界值为1以外，其余值都为0

In [15]:
Z = np.ones((5, 5))
Z[1:-1, 1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


16.给定一个数组，用0填充边界

In [16]:
Z = np.ones((3, 3))
Z = np.pad(Z, pad_width = 1, mode = 'constant', constant_values = 0)
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


17.运行以下表达式，观察结果

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 0.1 * 3)

nan
False
False
nan
False


18.创建一个5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置

In [18]:
Z = np.diag(1 + np.arange(4), k = -1) # k = -1表示填充下对角线
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19.创建一个8x8的矩阵，并且设置成棋盘样式

In [19]:
Z = np.zeros((8, 8), dtype = int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20.考虑一个(6, 7, 8)形状的数组，其第100个元素的索引(x, y, z)是什么？

In [20]:
print(np.unravel_index(100, (6, 7, 8)))

(1, 5, 4)


21.用tile函数创建一个8x8的棋盘样式矩阵

In [21]:
# Numpy的 tile() 函数，就是将原矩阵横向、纵向地复制。tile 是瓷砖的意思，顾名思义，这个函数就是把数组像瓷砖一样铺展开来。
Z = np.tile(np.array([[0, 1], [1, 0]]), (4, 4)) # 将数组[[0, 1], [1, 0]]横向，纵向都复制4份
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22.对一个5x5的随机矩阵做归一化

In [22]:
Z = np.random.random((5, 5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin) / (Zmax - Zmin)
print(Z)

[[0.33172151 0.58537408 0.7398602  0.77327393 0.90237171]
 [0.05461028 0.93575478 1.         0.62110292 0.12784003]
 [0.11765014 0.87331066 0.03859101 0.45094346 0.88476923]
 [0.03532713 0.81155213 0.91127844 0.60595496 0.        ]
 [0.2445004  0.80271315 0.71997433 0.48236201 0.18116223]]


23.创建一个将颜色描述为RGBA四个无符号字节的自定义dtype

In [23]:
color = np.dtype([('r', np.ubyte, 1), ('g', np.ubyte, 1), ('b', np.ubyte, 1), ('a', np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

24.计算一个5x3的矩阵和一个3x2的矩阵相乘

In [24]:
A = np.ones((5, 3))
B = np.ones((3, 2))
C = np.dot(A, B)
print(C)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


25.给定一个一维数组，对其在3到8之间的所有元素取反

In [25]:
Z = np.arange(12)
Z[(Z >= 3) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10 11]


26.下面脚本运行后的结果是什么？

In [26]:
# 当axis取负数的时候，对于二维矩阵，只能取-1和-2（不可超过矩阵的维度）。
# 当axis=-1时，相当于axis=1的效果，当axis=-2时，相当于axis=0的效果。
print(np.sum(range(5), -1))

10


27.考虑一个整数向量Z，下列表达合法的是哪个？

In [27]:
Z = np.arange(5)
#Z ** Z # 合法,每一位乘自己次方
#2 << Z >> 2 # 合法，每一个元素都移位
#Z < -Z # 合法，逐元素比较
#1j * Z # 合法，每个元素变成虚数
#Z / 1 / 1 # 合法，连除
Z < Z > Z # 不合法

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

28.下列表达式的结果分别是什么？

In [28]:
#np.array(0) / np.array(0) # nan
#np.array(0) // np.array(0) # 0
np.array([np.nan]).astype(int).astype(float) # array([-2.14748365e+09])

array([-2.14748365e+09])

29.如何从零位对浮点数组做舍入？

In [29]:
Z = np.random.uniform(-10, +10, 10)
print(np.copysign(np.ceil(np.abs(Z)), Z)) # np.copysign(arr1, arr2) 将arr1的符号逐元素改成arr2的符号

[-10.  -4.   7.  -7.   6.  -7. -10.  -3.  -9.  -5.]


30.如何找到两个数组中的共同元素？

In [30]:
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)
print(np.intersect1d(Z1, Z2))

[3 5 6 7 8 9]


31.如何忽略所有的numpy警告（尽管不建议这么做）？

In [31]:
# Suicide mode on
defaults = np.seterr(all = 'ignore')
Z = np.ones(1) / 0
# Back to sanity
_ = np.seterr(**defaults)

# 上下文管理器
with np.errstate(divide = 'ignore'):
    Z = np.ones(1) / 0

32.下面的表达式是正确的吗？

In [32]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\89500\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

33.如何得到昨天，今天，明天的日期？

In [33]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print('Yesterday is ' + str(yesterday))
print('Today is ' + str(today))
print('Tomorrow is ' + str(tomorrow))

Yesterday is 2020-01-25
Today is 2020-01-26
Tomorrow is 2020-01-27


34.如何得到所有与2016年7月对应的日期？

In [34]:
Z = np.arange('2016-07', '2016-08', dtype = 'datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


35.如何直接原地计算 (A+B) * (-A/2)

In [35]:
A = np.ones(3)
B = np.ones(3) * 2
C = np.ones(3) * 3
np.add(A, B, out = B)
np.divide(A, 2, out = A)
np.negative(A, out = A)
np.multiply(A, B, out = A)
print(A)

[-1.5 -1.5 -1.5]


36.用五种不同的方法提取一个随机数组的整数部分

In [36]:
Z = np.random.uniform(0, 10, 10)
print(Z - Z % 1)
print(np.floor(Z))
print(np.ceil(Z) - 1)
print(Z.astype(int))
print(np.trunc(Z))

[6. 7. 6. 5. 5. 1. 1. 5. 1. 4.]
[6. 7. 6. 5. 5. 1. 1. 5. 1. 4.]
[6. 7. 6. 5. 5. 1. 1. 5. 1. 4.]
[6 7 6 5 5 1 1 5 1 4]
[6. 7. 6. 5. 5. 1. 1. 5. 1. 4.]


37.创建一个5x5的矩阵，其中每行的数值范围从0-4

In [37]:
Z = np.zeros((5, 5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


38.通过考虑一个可生成10个整数的函数，来构建一个数组

In [38]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(), dtype = float, count = -1) # 从迭代器生成数组
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


39.创建一个长度为10的随机向量，其值域范围从0-1，但是不包括0和1

In [39]:
Z = np.random.random(10)
print(Z)
Z = np.random.uniform(0, 1, 10)
print(Z)

[0.89119246 0.54858931 0.81991355 0.95738709 0.50688    0.78451486
 0.46303797 0.06560875 0.48346308 0.07539806]
[0.46043274 0.57181133 0.30355808 0.63032894 0.60467086 0.04968906
 0.54364452 0.93390194 0.61856788 0.56621376]


40.创建一个长度为10的随机向量，并将其排序

In [40]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.15078179 0.1998268  0.36048741 0.45149478 0.49461623 0.63181607
 0.64317555 0.70316284 0.9398466  0.95019997]


41.对于一个小数组，如何用比np.sum更快的方式对其求和？

In [41]:
Z = np.arange(10)
np.add.reduce(Z)

45

42.对于两个随机数组A和B，检查它们是否相等

In [42]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
print(A, B)
equal1 = np.allclose(A, B)
equal2 = np.array_equal(A, B)
print(equal1, equal2)

[0 1 0 0 1] [1 1 1 1 1]
False False


43.创建一个只读数组

In [43]:
Z = np.ones(10)
Z.flags.writeable = False
Z[0] = 0

ValueError: assignment destination is read-only

44.将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式

In [44]:
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X ** 2 + Y ** 2)
T = np.arctan2(Y, X)
print(R)
print(T)

[0.99677644 1.3047834  1.05657597 0.57297046 0.95336468 0.9148462
 0.52538981 0.92736162 1.22405213 1.21480348]
[1.27691356 0.7136134  1.03616917 0.59537565 1.24248127 0.34496125
 0.59270802 1.16032259 0.75914809 0.91428048]


45.创建一个长度为10的向量，并将向量中最大值替换为1

In [45]:
Z = np.random.random(10)
Z[Z.argmax()] = 1
print(Z)

[0.33352921 0.82944545 0.11766274 1.         0.39444722 0.93193029
 0.73144908 0.34604619 0.92750435 0.61020892]


46.创建一个结构化数组，并实现x和y坐标覆盖[0,1]x[0,1]区域

In [46]:
Z = np.zeros((5, 5), [('x', float), ('y', float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


47.给定两个数组X, Y，构造Cauchy矩阵C（Cij = 1/(xi-yj)）

In [47]:
X = np.arange(8)
Y = X + 0.5

C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


48.打印每个numpy标量类型的最大值和最小值

In [48]:
for dtype in [np.int8, np.int32, np.int64]:
    print(str(dtype) + '最小值', np.iinfo(dtype).min)
    print(str(dtype) + '最大值', np.iinfo(dtype).max, '\n')
for dtype in [np.float32, np.float64]:
    print(str(dtype) + '最小值', np.finfo(dtype).min)
    print(str(dtype) + '最大值', np.finfo(dtype).max)
    print(str(dtype) + '精度', np.finfo(dtype).eps, '\n')

<class 'numpy.int8'>最小值 -128
<class 'numpy.int8'>最大值 127 

<class 'numpy.int32'>最小值 -2147483648
<class 'numpy.int32'>最大值 2147483647 

<class 'numpy.int64'>最小值 -9223372036854775808
<class 'numpy.int64'>最大值 9223372036854775807 

<class 'numpy.float32'>最小值 -3.4028235e+38
<class 'numpy.float32'>最大值 3.4028235e+38
<class 'numpy.float32'>精度 1.1920929e-07 

<class 'numpy.float64'>最小值 -1.7976931348623157e+308
<class 'numpy.float64'>最大值 1.7976931348623157e+308
<class 'numpy.float64'>精度 2.220446049250313e-16 



49.如何打印一个数组中所有的数值？

In [49]:
import sys
np.set_printoptions(threshold = sys.maxsize) # 强制NumPy打印完整数组，如果不设置的话，数组中间的值会被省略，显示为...
Z = np.zeros((24, 24))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.

50.给定标量时，如何找到数组中最接近这个标量的值？

In [50]:
Z = np.random.random((100, 100))
scalar = 0.5
index = (np.abs(Z - scalar)).argmin()
index = np.unravel_index(index, (100, 100))
print(Z[index])

0.5000474597698154


51.创建一个表示位置(x, y)和颜色(r, g, b)的结构化数组

In [51]:
Z = np.zeros(10, [('position', [('x', float, 1), ('y', float, 1)]), ('color', [('r', float, 1), ('g', float, 1), ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


52.对一个表示坐标形状为(10, 2)的随机向量（10个点，每个点二维），找到点与点的距离

In [52]:
Z = np.random.random((10, 2))
X, Y = np.atleast_2d(Z[:, 0], Z[:, 1])
print(X,'\n\n\n', Y, '\n\n\n', Z, '\n\n\n')
D = np.sqrt((X - X.T)**2 + (Y - Y.T)**2) # 十个点，两两距离矩阵
print(np.round(D, 3))

[[0.26714286 0.61888619 0.25949172 0.49209173 0.89711326 0.19511565
  0.10659188 0.26860401 0.21699369 0.67211185]] 


 [[0.18507115 0.24239229 0.55651161 0.08425934 0.27179623 0.79051194
  0.00350218 0.70763783 0.44004505 0.72247937]] 


 [[0.26714286 0.18507115]
 [0.61888619 0.24239229]
 [0.25949172 0.55651161]
 [0.49209173 0.08425934]
 [0.89711326 0.27179623]
 [0.19511565 0.79051194]
 [0.10659188 0.00350218]
 [0.26860401 0.70763783]
 [0.21699369 0.44004505]
 [0.67211185 0.72247937]] 



[[0.    0.356 0.372 0.247 0.636 0.61  0.242 0.523 0.26  0.673]
 [0.356 0.    0.477 0.203 0.28  0.693 0.565 0.582 0.448 0.483]
 [0.372 0.477 0.    0.526 0.698 0.243 0.574 0.151 0.124 0.445]
 [0.247 0.203 0.526 0.    0.446 0.766 0.394 0.662 0.45  0.663]
 [0.636 0.28  0.698 0.446 0.    0.873 0.835 0.765 0.701 0.504]
 [0.61  0.693 0.243 0.766 0.873 0.    0.792 0.111 0.351 0.482]
 [0.242 0.565 0.574 0.394 0.835 0.792 0.    0.723 0.45  0.915]
 [0.523 0.582 0.151 0.662 0.765 0.111 0.723 0.    0.273 0.404]
 

53.如何将32位的整数(integer)转换为对应的浮点数（float）?

In [53]:
Z = np.arange(10, dtype = np.int32)
Z = Z.astype(np.float32, copy = False)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


54.如何读取这样的文件？

    1,2,3,4,5
    6,,,7,8
    ,,9,10,11

In [54]:
Z = np.genfromtxt('test.txt')
print(Z)

[nan nan nan]


55.对于numpy数组，enumerate的等价操作是什么？

In [55]:
Z = np.arange(9).reshape((3, 3))

for index, value in np.ndenumerate(Z):
    print(index, value)
print('\n')
    
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


56.生成一个通用的二维Gaussian-like数组

In [56]:
X, Y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
D = np.sqrt(X*X + Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D - mu)**2 / (2.0 * sigma**2))) # 高斯分布的一个峰
print(np.round(G, 4))

[[0.3679 0.4482 0.5198 0.5738 0.6028 0.6028 0.5738 0.5198 0.4482 0.3679]
 [0.4482 0.5461 0.6333 0.6991 0.7344 0.7344 0.6991 0.6333 0.5461 0.4482]
 [0.5198 0.6333 0.7344 0.8107 0.8517 0.8517 0.8107 0.7344 0.6333 0.5198]
 [0.5738 0.6991 0.8107 0.8948 0.9401 0.9401 0.8948 0.8107 0.6991 0.5738]
 [0.6028 0.7344 0.8517 0.9401 0.9877 0.9877 0.9401 0.8517 0.7344 0.6028]
 [0.6028 0.7344 0.8517 0.9401 0.9877 0.9877 0.9401 0.8517 0.7344 0.6028]
 [0.5738 0.6991 0.8107 0.8948 0.9401 0.9401 0.8948 0.8107 0.6991 0.5738]
 [0.5198 0.6333 0.7344 0.8107 0.8517 0.8517 0.8107 0.7344 0.6333 0.5198]
 [0.4482 0.5461 0.6333 0.6991 0.7344 0.7344 0.6991 0.6333 0.5461 0.4482]
 [0.3679 0.4482 0.5198 0.5738 0.6028 0.6028 0.5738 0.5198 0.4482 0.3679]]


57.对一个二维数组，如何在其内部随机放置p个元素？

In [57]:
n = 10
p = 3
Z = np.zeros((n, n))
np.put(Z, np.random.choice(range(n*n), p, replace = False), 1)
print(Z)

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


58.减去一个矩阵中每一行的平均值

In [58]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis = 1, keepdims = True)
Z = X - X.mean(axis = 1).reshape((-1, 1)) # 均值重整为一列
print(np.round(Y, 3), '\n')
print(np.round(Z, 3))

[[-0.199  0.508 -0.18  -0.035 -0.251 -0.354  0.054  0.283 -0.099  0.273]
 [ 0.023  0.302 -0.279 -0.388 -0.266  0.089  0.357  0.239 -0.176  0.098]
 [-0.311  0.285 -0.473 -0.182  0.26   0.078  0.348 -0.553  0.304  0.244]
 [-0.272 -0.043  0.496 -0.387  0.04  -0.419  0.306 -0.195  0.335  0.138]
 [-0.131 -0.227  0.266  0.03  -0.536  0.348  0.271 -0.402  0.244  0.136]] 

[[-0.199  0.508 -0.18  -0.035 -0.251 -0.354  0.054  0.283 -0.099  0.273]
 [ 0.023  0.302 -0.279 -0.388 -0.266  0.089  0.357  0.239 -0.176  0.098]
 [-0.311  0.285 -0.473 -0.182  0.26   0.078  0.348 -0.553  0.304  0.244]
 [-0.272 -0.043  0.496 -0.387  0.04  -0.419  0.306 -0.195  0.335  0.138]
 [-0.131 -0.227  0.266  0.03  -0.536  0.348  0.271 -0.402  0.244  0.136]]


59.如何通过第n列对一个数组进行排序？

In [59]:
Z = np.random.randint(0, 10, (3,3))
print(Z, '\n')
print(Z[Z[:, 1].argsort()])

[[4 6 3]
 [9 4 8]
 [4 8 2]] 

[[9 4 8]
 [4 6 3]
 [4 8 2]]


60.如何检查一个二维数组是否有空列？

In [60]:
np.random.seed(0)
Z = np.random.randint(0, 3, (3, 10))
print(Z, '\n')
print(~Z, '\n')
print(~Z.any(axis = 0), '\n') # any()函数用于判断给定的可迭代参数iterable是否全部为False，则返回 False，如果有一个为 True，则返回 True。
print((~Z.any(axis = 0)).any())

[[0 1 0 1 1 2 0 2 0 0]
 [0 2 1 2 2 0 1 1 1 1]
 [0 1 0 0 1 2 0 2 0 1]] 

[[-1 -2 -1 -2 -2 -3 -1 -3 -1 -1]
 [-1 -3 -2 -3 -3 -1 -2 -2 -2 -2]
 [-1 -2 -1 -1 -2 -3 -1 -3 -1 -2]] 

[ True False False False False False False False False False] 

True


61.从数组的给定值中找出最近的值

In [61]:
Z = np.random.uniform(0, 1, 10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5218483217500717


62.如何用迭代器（iterator）计算两个分别具有形状(1,3), (3,1)的数组？

In [62]:
A = np.arange(3).reshape(3, 1)
B = np.arange(3).reshape(1, 3)
it = np.nditer([A, B, None])
for x, y, z in it:
    z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


63.创建一个具有name属性的数组类

In [63]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name = 'no name'):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None:
            return
        self.info = getattr(obj, 'name', 'no name')

Z = NamedArray(np.arange(10), 'range_10')
print(Z.name)

range_10


64.考虑一个给定的向量，如何对由第二个向量索引的每个元素+1（小心重复的索引）？

In [64]:
# np.bincount使用：我们可以看到x中最大的数为7，因此bin的数量为8，那么它的索引值为0->7
x = np.array([0, 1, 1, 3, 2, 1, 7])
# 索引0出现了1次，索引1出现了3次......索引5出现了0次......
np.bincount(x)
#因此，输出结果为：array([1, 3, 1, 1, 0, 0, 0, 1])

array([1, 3, 1, 1, 0, 0, 0, 1], dtype=int64)

In [65]:
Z = np.ones(10)
I = np.random.randint(0, len(Z), 20)
Z += np.bincount(I, minlength = len(Z))
print(Z)

[3. 4. 2. 2. 4. 3. 2. 3. 3. 4.]


65.根据索引列表（I），如何将向量（X）的元素累加到数组（F）？

In [66]:
X = [1, 2, 3, 4, 5, 6]
I = [1, 3, 9, 3, 4, 1]
F = np.bincount(I, weights = X) # 使用X进行加权，将I当作索引
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


66.考虑一个（dtype = ubyte）的（w, h, 3）图像，计算其唯一颜色的数量

In [67]:
w, h = 16, 16
I = np.random.randint(0, 2, (w, h, 3)).astype(np.ubyte)
# Note that we should compute 256*256 first. Otherwise numpy will only promote F.dtype to 'unit16' and overflow will occur
F = I[...,0] * (256 * 256) + I[..., 1] * 256 + I[..., 2] # 用17-24位表示第一个通道，9-16位表示第二个，1-8位表示第三个
n = len(np.unique(F))
print(n)

8


67.考虑一个四维数组，如何一次性计算出最后两个轴（axis）的和？

In [68]:
A = np.random.randint(0, 10, (3,4,3,4))
# 方法1
sum_1 = A.sum(axis = (-2, -1))
# 方法2
sum_2 = A.reshape(A.shape[:-2] + (-1,)).sum(axis = -1) # A.shape[:-2] = (3,4)，加上(-1,)为(3,4,-1)
print(sum_1, '\n\n', sum_2)

[[63 53 34 62]
 [33 44 65 63]
 [52 44 53 55]] 

 [[63 53 34 62]
 [33 44 65 63]
 [52 44 53 55]]


68.考虑一个一维向量D，如何使用相同大小的向量S来计算D子集的均值？

In [69]:
# 方法一
D = np.random.uniform(0, 1, 100)
S = np.random.randint(0, 10, 100) # S将D的元素分成很多类
D_sums = np.bincount(S, weights = D) # D的每类总和
D_counts = np.bincount(S) # D每一类样本数
D_means = D_sums / D_counts # D的类均值
print(D_means)

#方法二
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.51015081 0.69761199 0.42593295 0.44462607 0.47484426 0.62354907
 0.47297436 0.55353132 0.52882455 0.52069424]
0    0.510151
1    0.697612
2    0.425933
3    0.444626
4    0.474844
5    0.623549
6    0.472974
7    0.553531
8    0.528825
9    0.520694
dtype: float64


69.如何获得点积dot product的对角线？

In [70]:
A = np.random.uniform(0, 1, (5, 5))
B = np.random.uniform(0, 1, (5, 5))
# slow version
print(np.diag(np.dot(A, B))) # np.diag(M)取对角线元素构成新数组
# fast version
print(np.sum(A * B.T, axis = 1))
# faster version
print(np.einsum('ij,ji->i', A, B))

[0.4713291  1.42417978 1.25250407 1.66632515 0.72356109]
[0.4713291  1.42417978 1.25250407 1.66632515 0.72356109]
[0.4713291  1.42417978 1.25250407 1.66632515 0.72356109]


70.考虑一个向量[1,2,3,4,5]，如何建立一个新的向量，在这个新向量中每个值之间有3个连续的0？

In [71]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*nz) # 先创建一个全0向量
Z0[::nz+1] = Z                        # 再补值
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


71.考虑一个维度为(5, 5, 3)的数组，如何将其与一个(5, 5)的数组相乘（broadcast）？

In [72]:
A = np.ones((2, 5, 3))
B = 2 * np.ones((2, 5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


72.如何对一个数组中任意两行做交换？

In [73]:
A = np.arange(25).reshape((5, 5))
A[[0, 1]] = A[[1, 0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


73.考虑一个可以描述10个三角形的triplets，找到可以分割全部三角形的line segment

In [74]:
faces = np.random.randint(0, 100, (10, 3))
F = np.roll(faces.repeat(2, axis = 1), -1, axis = 1) # np.roll(A,2,axis=0)使A沿着轴滚动2格，例如12345 -> 45123
F = F.reshape(len(F)*3, 2)
F = np.sort(F, axis = 1)
G = F.view(dtype = [('p0', F.dtype), ('p1', F.dtype)])
G = np.unique(G)
print(G)

[( 4, 28) ( 4, 82) ( 6, 38) ( 6, 64) (15, 75) (15, 87) (17, 20) (17, 47)
 (20, 47) (20, 55) (20, 71) (28, 82) (29, 77) (29, 95) (38, 64) (41, 66)
 (41, 90) (44, 44) (44, 91) (49, 49) (49, 65) (55, 71) (57, 80) (57, 87)
 (66, 90) (75, 87) (77, 95) (80, 87)]


74.给定一个二进制的数组C，如何产生一个数组A满足np.bincount(A) == C？

In [75]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)),C)
print(A)

[1 1 2 3 4 4 6]


75.如何通过滑动窗口计算一个数组的平均数？

In [76]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype = float) # 前k个数累积和
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n-1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


76.考虑一维数组Z，构建一个有3列的二维数组，且第一行是(Z[0], Z[1], Z[2])，每个后续行移1（最后一行应该是(Z[-3], Z[-2], Z[-1])）

In [77]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape = shape, strides = strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


77.如何对布尔值取反，或者原位（in-place）改变浮点数的符号？

In [78]:
Z = np.random.randint(0, 2, 100) # 只取0/1
np.logical_not(Z, out = Z) # 原位，所以输出到自身
print(Z)

Z = np.random.uniform(-1.0, 1.0, 100)
np.negative(Z, out = Z)
print(np.round(Z, 3))

[1 1 0 1 1 1 1 1 0 1 0 1 1 0 1 0 0 0 0 0 0 1 0 1 1 0 0 0 1 0 0 1 0 1 0 1 0
 1 0 0 1 0 0 1 1 0 1 0 0 1 1 0 1 0 1 0 0 0 0 0 0 0 1 1 1 0 1 1 1 1 0 0 1 0
 0 0 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 0 1 0 1 1 0 0 1 0]
[-0.606  0.682 -0.211  0.769 -0.456 -0.275 -0.624  0.041 -0.83   0.901
  0.414 -0.43   0.164  0.654  0.786 -0.635  0.054 -0.765 -0.467  0.181
  0.253 -0.031 -0.778 -0.475  0.99  -0.388 -0.839 -0.421  0.646  0.033
  0.719  0.282 -0.874 -0.847  0.434  0.321 -0.2   -0.926  0.704  0.486
 -0.747  0.016 -0.798  0.629 -0.065  0.347  0.367  0.106  0.134  0.285
 -0.83  -0.463 -0.455  0.42  -0.155 -0.558 -0.591  0.311 -0.542 -0.472
  0.717 -0.732  0.117  0.027  0.103 -0.136 -0.242  0.004 -0.734 -0.255
  0.197  0.167 -0.622  0.304  0.577  0.881 -0.752 -0.837  0.76   0.331
  0.649  0.768 -0.8    0.886 -0.961  0.807 -0.727 -0.133  0.264  0.315
 -0.515  0.371 -0.315 -0.035  0.03  -0.802 -0.109 -0.654 -0.451  0.923]


78.考虑两组点集P0和P1去描述一组线（二维）和一个点p，如何计算点p到每一条线i（P0[i], P1[i]）的距离？

In [79]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis = 1)
    U = -((P0[:,0] - p[...,0]) * T[:,0] + (P0[:,1] - p[...,1]) * T[:,1]) / L
    U = U.reshape(len(U), 1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis = 1))

P0 = np.random.uniform(-10, 10, (10,2)) # 十个点
P1 = np.random.uniform(-10, 10, (10,2)) # 十个点
p = np.random.uniform(-10, 10, (1, 2))
print(distance(P0, P1, p))

[13.03744236  3.51363942  6.44910496  7.52353778 10.52077005  2.03870786
  3.97162606  0.59735107 10.82770604  5.55643309]


79.考虑两组点集P0和P1去描述一组线和一组点集P，如何计算每一个点j（P[j]）到每一条线i的距离？

In [80]:
P0 = np.random.uniform(-10, 10, (10,2)) # 十个点
P1 = np.random.uniform(-10, 10, (10,2)) # 十个点
p = np.random.uniform(-10, 10, (10, 2))

print(np.round(np.array([distance(P0, P1, p_i) for p_i in p]), 3))

[[ 1.958  7.982  1.278  0.835  2.198  0.94   9.199  9.786  0.52   8.126]
 [ 3.717  1.002  9.898  4.842  2.022  9.057  6.262  5.773  7.69   1.836]
 [ 1.775  1.908 10.943 10.199  6.625 13.639  9.787  8.749 12.207  3.435]
 [ 0.343  5.26   4.483  0.937  1.797  3.697  7.825  8.043  2.277  6.114]
 [10.725  4.933 13.311  1.359  6.416  5.758  1.927  2.083  4.569  7.504]
 [ 6.723  2.273 13.328  5.775  0.639 11.264  3.99   3.193  9.957  0.614]
 [14.756  8.84  16.603  2.499  9.758  6.309  5.798  6.068  5.21   8.296]
 [13.342  6.838 13.747  5.209 10.521  2.98   5.514  5.353  1.865 11.181]
 [ 0.797  6.426  3.385  0.954  2.552  3.233  8.814  9.103  1.79   6.201]
 [ 0.112  7.538  1.242  9.115  4.307  6.535  4.554  6.05   7.912 16.356]]


80.考虑一个任意数组，写一个函数，提取一个固定形状的子部分，并以给定元素为中心（fill必要时填充一个值）

In [81]:
Z = np.random.randint(0, 10, (10, 10))
shape = (5, 5)
fill = 0
position = (1, 1)
R = np.ones(shape, dtype = Z.dtype) * fill
P = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)
R_start = np.zeros((len(shape),)).astype(int)
R_stop = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop = (P+Rs//2) + Rs%2
R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()
r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]

R[r] = Z[z]

print (Z)
print (R)

[[9 0 3 0 7 0 8 1 2 8]
 [5 8 2 1 3 5 0 2 5 8]
 [6 2 7 7 1 8 4 9 3 3]
 [2 9 0 4 6 4 3 2 3 1]
 [1 2 7 2 7 0 1 8 0 5]
 [2 8 0 4 0 3 8 1 6 4]
 [6 9 6 4 7 2 9 8 0 8]
 [6 2 6 9 5 3 7 8 3 8]
 [8 9 9 4 4 1 0 7 6 2]
 [1 0 6 1 6 7 1 5 2 0]]
[[0 0 0 0 0]
 [0 9 0 3 0]
 [0 5 8 2 1]
 [0 6 2 7 7]
 [0 2 9 0 4]]


C:\Users\89500\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


81. 考虑一个数组Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14],如何生成一个数组R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ...,[11,12,13,14]]?

In [82]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))

print (R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


82. 计算一个矩阵的秩

In [83]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10) # 非0特征值的数量

print (rank)

10


83. 如何找到一个数组中出现频率最高的值？

In [84]:
Z = np.random.randint(0,10,50)
print (np.bincount(Z).argmax())

3


84. 从一个10x10的矩阵中提取出连续的3x3区块

In [85]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)

print (C)

[[[[1 1 1]
   [1 0 0]
   [3 0 1]]

  [[1 1 0]
   [0 0 1]
   [0 1 2]]

  [[1 0 3]
   [0 1 4]
   [1 2 4]]

  [[0 3 3]
   [1 4 3]
   [2 4 3]]

  [[3 3 4]
   [4 3 2]
   [4 3 3]]

  [[3 4 2]
   [3 2 4]
   [3 3 4]]

  [[4 2 0]
   [2 4 2]
   [3 4 2]]

  [[2 0 3]
   [4 2 2]
   [4 2 2]]]


 [[[1 0 0]
   [3 0 1]
   [2 4 2]]

  [[0 0 1]
   [0 1 2]
   [4 2 4]]

  [[0 1 4]
   [1 2 4]
   [2 4 3]]

  [[1 4 3]
   [2 4 3]
   [4 3 4]]

  [[4 3 2]
   [4 3 3]
   [3 4 1]]

  [[3 2 4]
   [3 3 4]
   [4 1 0]]

  [[2 4 2]
   [3 4 2]
   [1 0 0]]

  [[4 2 2]
   [4 2 2]
   [0 0 1]]]


 [[[3 0 1]
   [2 4 2]
   [4 0 1]]

  [[0 1 2]
   [4 2 4]
   [0 1 2]]

  [[1 2 4]
   [2 4 3]
   [1 2 1]]

  [[2 4 3]
   [4 3 4]
   [2 1 0]]

  [[4 3 3]
   [3 4 1]
   [1 0 4]]

  [[3 3 4]
   [4 1 0]
   [0 4 4]]

  [[3 4 2]
   [1 0 0]
   [4 4 4]]

  [[4 2 2]
   [0 0 1]
   [4 4 0]]]


 [[[2 4 2]
   [4 0 1]
   [2 4 3]]

  [[4 2 4]
   [0 1 2]
   [4 3 2]]

  [[2 4 3]
   [1 2 1]
   [3 2 1]]

  [[4 3 4]
   [2 1 0]
   [2 1 3]]

  [[3 4 1]
   

85. 创建一个满足 Z[i,j] == Z[j,i]的子类（对称矩阵）

In [86]:
class Symetric(np.ndarray):

    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42

print (S)

[[ 6 12  4  9  8]
 [12  5  8 13  3]
 [ 4  8  0 42  6]
 [ 9 13 10  4 13]
 [ 8  3  6 13  5]]


86. 考虑p个 nxn 矩阵和一组形状为(n,1)的向量，如何直接计算p个矩阵的乘积(n,1)？

In [87]:
p, n = 10, 20

M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])

print (S)

# It works, because: M is (p,n,n)， V is (p,n,1)

# Thus, summing over the paired axes 0 and 0 (of M and V independently), and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


87. 对于一个16x16的数组，如何得到一个区域(block-sum)的和(区域大小为4x4)?

In [88]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0), np.arange(0, Z.shape[1], k), axis=1)

print (S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


88. 如何利用numpy数组实现Game of Life?

In [90]:
import time
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] + Z[1:-1,0:-2] + Z[1:-1,2:] + Z[2: ,0:-2] + Z[2: ,1:-1] + Z[2: ,2:])
    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): 
    Z = iterate(Z)
    print (Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1
  0 1 0 1 0 1 0 1 0 0 0 1 0 0]
 [0 0 1 0 0 0 1 1 0 1 1 0 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0
  0 0 0 0 1 0 0 1 1 0 0 1 1 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0
  0 0 1 1 0 0 0 0 1 1 1 1 0 0]
 [0 0 1 0 1 0 0 0 1 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0 0
  0 1 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0
  0 1 0 0 1 1 1 1 1 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0
  0 0 1 0 0 0 0 0 1 0 1 0 0 0]
 [0 1 1 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 1 0 0 0 0 1 0 1 1 0 0
  0 0 1 0 1 0 0 0 0 0 1 1 0 0]
 [0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 1 0
  0 0 0 0 1 0 1 0 0 0 1 1 1 0]
 [0 1 1 1 0 1 1 0 0 0 1 0 1 0 1 1 1 1 1 0 1 0 0 0 1 0 1

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

89. 如何找到一个数组的第n个最大值?

In [91]:
Z = np.arange(10000)
np.random.shuffle(Z)

n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9997 9998 9999 9996 9995]


90. 给定任意个数向量，创建笛卡尔积(每一个元素的每一种组合)

In [92]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


91. 如何从一个正常数组创建记录数组(record array)?

In [93]:
Z = np.array([("Hello", 2.5, 3), ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, names='col1, col2, col3', formats = 'S8, f8, i8')

print (R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


92. 考虑一个大向量Z, 用三种不同的方法计算它的立方

In [94]:
x = np.random.rand((10))
print(np.power(x,3))

# 方法2
print( x * x * x )

# 方法3
print(np.einsum('i,i,i->i',x,x,x))

[0.1173737  0.83137078 0.77590832 0.54677974 0.0111281  0.0233867
 0.56976077 0.27743633 0.01487586 0.65651005]
[0.1173737  0.83137078 0.77590832 0.54677974 0.0111281  0.0233867
 0.56976077 0.27743633 0.01487586 0.65651005]
[0.1173737  0.83137078 0.77590832 0.54677974 0.0111281  0.0233867
 0.56976077 0.27743633 0.01487586 0.65651005]


93. 考虑两个形状分别为(8,3) 和(2,2)的数组A和B. 如何在数组A中找到满足包含B中元素的行？(不考虑B中每行元素顺序)？

In [95]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]

print (rows)

[4 7]


94. 考虑一个10x3的矩阵，分解出有不全相同值的行 (如 [2,2,3])

In [96]:
Z = np.random.randint(2,4,(10,3))
print (Z, '\n')

# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print (U, '\n')

# 方法2
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print (U)

[[2 3 2]
 [3 3 3]
 [3 2 2]
 [2 3 3]
 [2 2 2]
 [3 2 2]
 [3 3 2]
 [3 2 3]
 [3 3 2]
 [2 3 2]] 

[[2 3 2]
 [3 2 2]
 [2 3 3]
 [3 2 2]
 [3 3 2]
 [3 2 3]
 [3 3 2]
 [2 3 2]] 

[[2 3 2]
 [3 2 2]
 [2 3 3]
 [3 2 2]
 [3 3 2]
 [3 2 3]
 [3 3 2]
 [2 3 2]]


95. 将一个整数向量转换为matrix binary的表现形式

In [97]:
# 方法1
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype = np.ubyte)
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1], '\n')

# 方法2
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]] 

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


96. 给定一个二维数组，如何提取出唯一的(unique)行？

In [98]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]

print (uZ)

[[0 0 1]
 [0 1 0]
 [0 1 1]
 [1 1 0]
 [1 1 1]]


97. 考虑两个向量A和B，写出用einsum等式对应的inner, outer, sum, mul函数

In [99]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

print ('sum')
print (np.einsum('i->', A), '\n') # np.sum(A)

print ('A * B')
print (np.einsum('i,i->i', A, B), '\n') # A * B

print ('inner')
print (np.einsum('i,i', A, B), '\n') # np.inner(A, B)

print ('outer')
print (np.einsum('i,j->ij', A, B), '\n') # np.outer(A, B)

sum
4.7609721446540805 

A * B
[0.00173922 0.06608329 0.01022572 0.69739132 0.0180214  0.12959454
 0.42905897 0.0032382  0.19116284 0.15551875] 

inner
1.7020342544742544 

outer
[[1.73921765e-03 4.07419635e-02 1.46774426e-02 3.71053042e-01
  1.18278640e-01 7.27137259e-02 2.11933690e-01 3.35177640e-01
  3.80678197e-01 6.69426095e-02]
 [2.82100352e-03 6.60832888e-02 2.38067484e-02 6.01846431e-01
  1.91847443e-01 1.17941349e-01 3.43755529e-01 5.43656683e-01
  6.17458390e-01 1.08580623e-01]
 [1.21170675e-03 2.83847809e-02 1.02257220e-02 2.58511333e-01
  8.24043073e-02 5.06593940e-02 1.47653447e-01 2.33517068e-01
  2.65217145e-01 4.66386777e-02]
 [3.26884613e-03 7.65742054e-02 2.75861398e-02 6.97391323e-01
  2.22303789e-01 1.36664886e-01 3.98327731e-01 6.29963782e-01
  7.15481728e-01 1.25818117e-01]
 [2.64994012e-04 6.20760510e-03 2.23631262e-03 5.65350945e-02
  1.80213967e-02 1.10789480e-02 3.22910469e-02 5.10689777e-02
  5.80016208e-02 1.01996381e-02]
 [3.09973271e-03 7.26126468e-02 2.61

98. 考虑一个由两个向量描述的路径(X,Y)，如何用等距样例(equidistant samples)对其进行采样(sample)?

In [100]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr) # integrate path

r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x) # integrate path
y_int = np.interp(r_int, r, y)

99. 给定整数n和2D数组X，从X中选择可以解释为具有n度的多项分布的绘制的行，即，仅包含整数并且总和为n的行。

In [101]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0], [2.0, 0.0, 1.0, 1.0], [1.5, 2.5, 1.0, 0.0]])

n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)

print (X[M])

[[2. 0. 1. 1.]]


100. 计算1D阵列X的平均值的自举95％置信区间（即，对替换N次的阵列的元素进行重新采样，计算每个样本的平均值，然后计算均值上的百分位数）。

In [102]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples

idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])

print (confint)

[-0.3785393   0.01877697]
